# Site settings. Restart `jekyll serve` after editing; this file is not reloaded.

title: opencdsi.org
email: info@opencdsi.org
author: Dennis Dunn
tagline: Open Clinical Decision Support for Immunizations
description: >- # this means to ignore newlines until "baseurl:"
  OpenCdsi is  building a simple immunization decision support system
  for use by off-grid clinics and itinerant health workers. Its premier product is 
  VaxEngine, a vaccine forecasting tool. VaxEngine is used in the mobile app which
  includes  a basic immunization registry 
  and vaccine guidance from the <i>Pink Book</i>. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opencdsi.org" # the base hostname & protocol for your site, e.g. http://example.com

# Render settings
show_products: true

# Build settings
theme: 
plugins:
  - jekyll-feed

collections:
  products:
    output: true

show_excerpts: true

defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Dennis Dunn
