theme: minima
title: OpenCDSi
description: Open-sourced immunization decision support system based on the CDC CDSi Logic Spec.
logo: /assets/img/logo.png
email: info@opencdsi.org
show_excerpts: false
github_username:  opencdsi
